import express from 'express';
import Groq from 'groq-sdk';
import dotenv from 'dotenv';

dotenv.config();
const router = express.Router();

// Initialize Groq implicitly using the configured environment variable
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY || "gsk_dummy" });

router.post('/', async (req, res) => {
  try {
    const { messages } = req.body;
    
    // Strict Input Validation
    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: 'Messages array is fundamentally required.' });
    }

    // Configure system intelligence to mimic a doctor persona securely
    // --- HACKATHON MEMORY SYSTEM --- 
    // Inject the global active report text straight into the AI's internal brain!
    const activeData = global.latestReportContext ? `\n\nPatient's Latest Uploaded Medical Report Details to Reference:\n"${global.latestReportContext}"` : '';

    const systemMessage = {
      role: 'system',
      content: 'You are MedTwin AI, a highly intelligent, empathetic, and professional medical AI assistant. Offer clear, concise, and extremely helpful advice while maintaining a caring tone. Remind users you are an AI and they should consult doctors for emergencies. Maintain short, readable paragraphs.' + activeData
    };

    // Prepend system instruction to chat history sequentially securely
    const conversation = [systemMessage, ...messages];

    // Authorize API key presence algorithmically before pinging servers
    if (process.env.GROQ_API_KEY && process.env.GROQ_API_KEY.startsWith('gsk_')) {
      const chatCompletion = await groq.chat.completions.create({
        messages: conversation,
        model: "llama-3.1-8b-instant",
      });
      
      const aiReply = chatCompletion.choices[0]?.message?.content || "No output generated by architecture.";
      
      res.json({
        success: true,
        reply: aiReply
      });
    } else {
        res.status(401).json({ error: "Invalid API Key mapped inside Node environment." });
    }

  } catch (err) {
    console.error("Chat Integration Error: ", err);
    res.status(500).json({ error: 'Failed to negotiate stream with language model.' });
  }
});

export default router;
